/**
 * Seed complet — données issues de NOVACAMPUS_ALLIANCE_DATABASE.xlsx
 * Commande : npx prisma db seed  (depuis la racine)
 *            ou npm run prisma:seed (depuis services/academic-service/)
 */

import { PrismaClient, Role } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const passwordHashCache = new Map<string, string>();

function seedPassword(role: Role, firstName: string): string {
  switch (role) {
    case Role.ADMIN:
      return `Admin${firstName}2026!`;
    case Role.DIRECTION:
      return `Dir${firstName}2026!`;
    case Role.INSTRUCTOR:
      return `Prof${firstName}2026!`;
    case Role.STUDENT:
      return `Etu${firstName}2026!`;
    default:
      return `Nova${firstName}2026!`;
  }
}

async function hashPassword(plain: string): Promise<string> {
  const cached = passwordHashCache.get(plain);
  if (cached) return cached;
  const hash = await bcrypt.hash(plain, 10);
  passwordHashCache.set(plain, hash);
  return hash;
}

const DAY: Record<string, number> = {
  Lundi: 1,
  Mardi: 2,
  Mercredi: 3,
  Jeudi: 4,
  Vendredi: 5,
  Samedi: 6,
  Dimanche: 7,
};

function t(hms: string): Date {
  return new Date(`1970-01-01T${hms}Z`);
}

function mapPaymentStatus(s: string): string {
  switch (s) {
    case 'Payé':       return 'paye';
    case 'Retard':     return 'en_retard';
    case 'En attente': return 'en_attente';
    default:           return 'en_attente';
  }
}

function mapEnrollmentStatus(s: string): string {
  switch (s) {
    case 'En cours':  return 'inscrit';
    case 'Validé':    return 'valide';
    case 'Abandonné': return 'abandonne';
    case 'Échec':     return 'echec';
    default:          return 'inscrit';
  }
}

async function main() {
  const seededPasswords: { email: string; password: string }[] = [];

  // ─── Nettoyage (ordre inverse des dépendances FK) ──────────────
  await prisma.relanceHistory.deleteMany();
  await prisma.notification.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.enrollment.deleteMany();
  await prisma.schedule.deleteMany();
  await prisma.course.deleteMany();
  await prisma.user.deleteMany();
  await prisma.student.deleteMany();
  await prisma.room.deleteMany();
  await prisma.instructor.deleteMany();
  await prisma.kpiDashboard.deleteMany();
  await prisma.program.deleteMany();
  await prisma.campus.deleteMany();

  // ─── CAMPUS ────────────────────────────────────────────────────
  await prisma.campus.createMany({
    data: [
      {
        campus_id:         'CAMP001',
        campus_name:       'Campus Paris Centre',
        address:           '45 Boulevard Éducation',
        city:              'Paris',
        postal_code:       '75006',
        region:            'Île-de-France',
        campus_director:   'Dr. Philippe Mercier',
        phone:             '33170111111',
        email:             'p.mercier@novacampus.fr',
        capacity_students: 1200,
        opening_date:      new Date('2018-09-01'),
        status:            'Actif',
      },
      {
        campus_id:         'CAMP002',
        campus_name:       'Campus Lyon Confluence',
        address:           '78 Quai Savoir',
        city:              'Lyon',
        postal_code:       '69002',
        region:            'Auvergne-Rhône-Alpes',
        campus_director:   'Dr. Isabelle Fournier',
        phone:             '33170222222',
        email:             'i.fournier@novacampus.fr',
        capacity_students: 800,
        opening_date:      new Date('2019-09-01'),
        status:            'Actif',
      },
      {
        campus_id:         'CAMP003',
        campus_name:       'Campus Toulouse Aerospace',
        address:           '23 Avenue Innovation',
        city:              'Toulouse',
        postal_code:       '31400',
        region:            'Occitanie',
        campus_director:   'Dr. Bernard Rousseau',
        phone:             '33170333333',
        email:             'b.rousseau@novacampus.fr',
        capacity_students: 600,
        opening_date:      new Date('2021-09-01'),
        status:            'Actif',
      },
      {
        campus_id:         'CAMP004',
        campus_name:       'Campus Marseille Méditerranée',
        address:           '56 Rue Académique',
        city:              'Marseille',
        postal_code:       '13008',
        region:            "Provence-Alpes-Côte d'Azur",
        campus_director:   'Dr. Caroline Faure',
        phone:             '33170444444',
        email:             'c.faure@novacampus.fr',
        capacity_students: 500,
        opening_date:      new Date('2022-09-01'),
        status:            'Actif',
      },
    ],
  });

  // ─── PROGRAMMES ────────────────────────────────────────────────
  await prisma.program.createMany({
    data: [
      {
        program_id:     'PROG001',
        campus_id:      'CAMP001',
        program_name:   'Bachelor Commerce International',
        program_type:   'Bachelor',
        duration_years: 3,
        annual_tuition: 8500,
        department:     'Business',
        coordinator:    'Prof. Jean Mercier',
        max_students:   120,
        status:         'Actif',
      },
      {
        program_id:     'PROG002',
        campus_id:      'CAMP001',
        program_name:   'Bachelor Informatique & IA',
        program_type:   'Bachelor',
        duration_years: 3,
        annual_tuition: 9000,
        department:     'Technology',
        coordinator:    'Prof. Marie Dubois',
        max_students:   100,
        status:         'Actif',
      },
      {
        program_id:     'PROG003',
        campus_id:      'CAMP001',
        program_name:   'Master Finance de Marché',
        program_type:   'Master',
        duration_years: 2,
        annual_tuition: 12000,
        department:     'Business',
        coordinator:    'Prof. Pierre Laurent',
        max_students:   60,
        status:         'Actif',
      },
      {
        program_id:     'PROG004',
        campus_id:      'CAMP003',
        program_name:   'Bachelor Ingénierie Aérospatiale',
        program_type:   'Bachelor',
        duration_years: 3,
        annual_tuition: 9500,
        department:     'Engineering',
        coordinator:    'Prof. Sophie Rousseau',
        max_students:   80,
        status:         'Actif',
      },
      {
        program_id:     'PROG005',
        campus_id:      'CAMP004',
        program_name:   'Bachelor Tourisme International',
        program_type:   'Bachelor',
        duration_years: 3,
        annual_tuition: 7500,
        department:     'Hospitality',
        coordinator:    'Prof. Luc Faure',
        max_students:   70,
        status:         'Actif',
      },
      {
        program_id:     'PROG006',
        campus_id:      'CAMP002',
        program_name:   'Master Data Science',
        program_type:   'Master',
        duration_years: 2,
        annual_tuition: 13000,
        department:     'Technology',
        coordinator:    'Prof. Claire Martin',
        max_students:   50,
        status:         'Actif',
      },
      {
        program_id:     'PROG007',
        campus_id:      'CAMP002',
        program_name:   'Bachelor Marketing Digital',
        program_type:   'Bachelor',
        duration_years: 3,
        annual_tuition: 8000,
        department:     'Business',
        coordinator:    'Prof. Thomas Bernard',
        max_students:   90,
        status:         'Actif',
      },
    ],
  });

  // ─── ENSEIGNANTS ───────────────────────────────────────────────
  await prisma.instructor.createMany({
    data: [
      {
        instructor_id:  'INST001',
        campus_id:      'CAMP001',
        first_name:     'Jean',
        last_name:      'Mercier',
        email:          'j.mercier@novacampus.fr',
        phone:          '33180111111',
        department:     'Business',
        specialization: 'Commerce International',
        hire_date:      new Date('2018-09-01'),
        status:         'Actif',
      },
      {
        instructor_id:  'INST002',
        campus_id:      'CAMP001',
        first_name:     'Marie',
        last_name:      'Dubois',
        email:          'm.dubois@novacampus.fr',
        phone:          '33180222222',
        department:     'Technology',
        specialization: 'Intelligence Artificielle',
        hire_date:      new Date('2019-01-15'),
        status:         'Actif',
      },
      {
        instructor_id:  'INST003',
        campus_id:      'CAMP001',
        first_name:     'Pierre',
        last_name:      'Laurent',
        email:          'p.laurent@novacampus.fr',
        phone:          '33180333333',
        department:     'Business',
        specialization: 'Finance',
        hire_date:      new Date('2018-09-01'),
        status:         'Actif',
      },
      {
        instructor_id:  'INST004',
        campus_id:      'CAMP003',
        first_name:     'Sophie',
        last_name:      'Rousseau',
        email:          's.rousseau@novacampus.fr',
        phone:          '33180444444',
        department:     'Engineering',
        specialization: 'Aérospatial',
        hire_date:      new Date('2021-09-01'),
        status:         'Actif',
      },
      {
        instructor_id:  'INST005',
        campus_id:      'CAMP002',
        first_name:     'Claire',
        last_name:      'Martin',
        email:          'c.martin@novacampus.fr',
        phone:          '33180555555',
        department:     'Technology',
        specialization: 'Data Science',
        hire_date:      new Date('2019-09-01'),
        status:         'Actif',
      },
      {
        instructor_id:  'INST006',
        campus_id:      'CAMP001',
        first_name:     'Thomas',
        last_name:      'Bernard',
        email:          't.bernard@novacampus.fr',
        phone:          '33180666666',
        department:     'Business',
        specialization: 'Économie',
        hire_date:      new Date('2019-03-10'),
        status:         'Actif',
      },
      {
        instructor_id:  'INST007',
        campus_id:      'CAMP001',
        first_name:     'Luc',
        last_name:      'Faure',
        email:          'l.faure@novacampus.fr',
        phone:          '33180777777',
        department:     'Law',
        specialization: 'Droit des Affaires',
        hire_date:      new Date('2020-01-20'),
        status:         'Actif',
      },
      {
        instructor_id:  'INST008',
        campus_id:      'CAMP002',
        first_name:     'Julie',
        last_name:      'Simon',
        email:          'j.simon@novacampus.fr',
        phone:          '33180888888',
        department:     'Business',
        specialization: 'Marketing',
        hire_date:      new Date('2019-09-01'),
        status:         'Actif',
      },
    ],
  });

  // ─── SALLES ────────────────────────────────────────────────────
  await prisma.room.createMany({
    data: [
      {
        room_id:   'ROOM101',
        campus_id: 'CAMP001',
        room_name: 'Amphi Commerce A',
        building:  'Bâtiment A',
        floor:     1,
        capacity:  120,
        room_type: 'Amphithéâtre',
        equipment: 'Projecteur, Micro, Tableau interactif',
        status:    'Disponible',
      },
      {
        room_id:   'ROOM102',
        campus_id: 'CAMP001',
        room_name: 'Salle TD Commerce 1',
        building:  'Bâtiment A',
        floor:     1,
        capacity:  40,
        room_type: 'Salle TD',
        equipment: 'Projecteur, Tableau blanc',
        status:    'Disponible',
      },
      {
        room_id:   'ROOM201',
        campus_id: 'CAMP002',
        room_name: 'Salle Data Science',
        building:  'Bâtiment B',
        floor:     2,
        capacity:  30,
        room_type: 'Lab Informatique',
        equipment: '30 PC, Projecteur',
        status:    'Disponible',
      },
      {
        room_id:   'ROOM205',
        campus_id: 'CAMP001',
        room_name: 'Amphi Finance',
        building:  'Bâtiment B',
        floor:     2,
        capacity:  80,
        room_type: 'Amphithéâtre',
        equipment: 'Projecteur, Système audio',
        status:    'Disponible',
      },
      {
        room_id:   'ROOM206',
        campus_id: 'CAMP001',
        room_name: 'Salle Droit',
        building:  'Bâtiment B',
        floor:     2,
        capacity:  35,
        room_type: 'Salle TD',
        equipment: 'Projecteur, Tableau blanc',
        status:    'Disponible',
      },
      {
        room_id:   'ROOM302',
        campus_id: 'CAMP001',
        room_name: 'Lab Python 1',
        building:  'Bâtiment C',
        floor:     3,
        capacity:  35,
        room_type: 'Lab Informatique',
        equipment: '35 PC, Projecteur',
        status:    'Disponible',
      },
      {
        room_id:   'ROOM303',
        campus_id: 'CAMP001',
        room_name: 'Lab IA',
        building:  'Bâtiment C',
        floor:     3,
        capacity:  30,
        room_type: 'Lab Informatique',
        equipment: '30 PC GPU, Serveurs',
        status:    'Disponible',
      },
      {
        room_id:   'ROOM304',
        campus_id: 'CAMP001',
        room_name: 'Lab Web Dev',
        building:  'Bâtiment C',
        floor:     3,
        capacity:  32,
        room_type: 'Lab Informatique',
        equipment: '32 PC, Projecteur',
        status:    'Disponible',
      },
      {
        room_id:   'ROOM401',
        campus_id: 'CAMP003',
        room_name: 'Lab Aéro Mécanique',
        building:  'Bâtiment D',
        floor:     4,
        capacity:  25,
        room_type: 'Lab Technique',
        equipment: 'Équipements mécanique, Projecteur',
        status:    'Disponible',
      },
      {
        room_id:   'ROOM501',
        campus_id: 'CAMP004',
        room_name: 'Salle Tourisme',
        building:  'Bâtiment E',
        floor:     5,
        capacity:  45,
        room_type: 'Salle TD',
        equipment: 'Projecteur, Tableau interactif',
        status:    'Disponible',
      },
    ],
  });

  // ─── ÉTUDIANTS ─────────────────────────────────────────────────
  await prisma.student.createMany({
    data: [
      {
        student_id:        'STU001',
        campus_id:         'CAMP001',
        program_id:        'PROG001',
        first_name:        'Alexandre',
        last_name:         'Dubois',
        email:             'a.dubois@etu.novacampus.fr',
        birth_date:        new Date('2003-05-15'),
        enrollment_year:   2023,
        status:            'Actif',
        payment_status:    'À jour',
        address:           '12 Rue Étudiante',
        city:              'Paris',
        postal_code:       '75015',
        emergency_contact: 'Marie Dubois',
        emergency_phone:   '33620111111',
      },
      {
        student_id:        'STU002',
        campus_id:         'CAMP001',
        program_id:        'PROG002',
        first_name:        'Camille',
        last_name:         'Martin',
        email:             'c.martin@etu.novacampus.fr',
        birth_date:        new Date('2004-03-22'),
        enrollment_year:   2023,
        status:            'Actif',
        payment_status:    'Retard',
        address:           '34 Avenue Jeunesse',
        city:              'Paris',
        postal_code:       '75011',
        emergency_contact: 'Jean Martin',
        emergency_phone:   '33620222222',
      },
      {
        student_id:        'STU003',
        campus_id:         'CAMP002',
        program_id:        'PROG001',
        first_name:        'Lucas',
        last_name:         'Bernard',
        email:             'l.bernard@etu.novacampus.fr',
        birth_date:        new Date('2002-11-08'),
        enrollment_year:   2022,
        status:            'Actif',
        payment_status:    'À jour',
        address:           '56 Boulevard Campus',
        city:              'Lyon',
        postal_code:       '69003',
        emergency_contact: 'Sophie Bernard',
        emergency_phone:   '33620333333',
      },
      {
        student_id:        'STU004',
        campus_id:         'CAMP002',
        program_id:        'PROG003',
        first_name:        'Emma',
        last_name:         'Petit',
        email:             'e.petit@etu.novacampus.fr',
        birth_date:        new Date('2003-07-19'),
        enrollment_year:   2023,
        status:            'Actif',
        payment_status:    'À jour',
        address:           '78 Rue Université',
        city:              'Lyon',
        postal_code:       '69007',
        emergency_contact: 'Pierre Petit',
        emergency_phone:   '33620444444',
      },
      {
        student_id:        'STU005',
        campus_id:         'CAMP003',
        program_id:        'PROG004',
        first_name:        'Thomas',
        last_name:         'Roux',
        email:             't.roux@etu.novacampus.fr',
        birth_date:        new Date('2004-01-30'),
        enrollment_year:   2023,
        status:            'Actif',
        payment_status:    'À jour',
        address:           '90 Chemin Aéro',
        city:              'Toulouse',
        postal_code:       '31000',
        emergency_contact: 'Julie Roux',
        emergency_phone:   '33620555555',
      },
      {
        student_id:        'STU006',
        campus_id:         'CAMP001',
        program_id:        'PROG001',
        first_name:        'Léa',
        last_name:         'Moreau',
        email:             'l.moreau@etu.novacampus.fr',
        birth_date:        new Date('2003-09-12'),
        enrollment_year:   2023,
        status:            'Actif',
        payment_status:    'À jour',
        address:           '23 Rue Sorbonne',
        city:              'Paris',
        postal_code:       '75005',
        emergency_contact: 'Luc Moreau',
        emergency_phone:   '33620666666',
      },
      {
        student_id:        'STU007',
        campus_id:         'CAMP002',
        program_id:        'PROG002',
        first_name:        'Hugo',
        last_name:         'Simon',
        email:             'h.simon@etu.novacampus.fr',
        birth_date:        new Date('2002-06-25'),
        enrollment_year:   2022,
        status:            'Actif',
        payment_status:    'Retard',
        address:           '45 Avenue Étude',
        city:              'Lyon',
        postal_code:       '69001',
        emergency_contact: 'Claire Simon',
        emergency_phone:   '33620777777',
      },
      {
        student_id:        'STU008',
        campus_id:         'CAMP003',
        program_id:        'PROG004',
        first_name:        'Chloé',
        last_name:         'Laurent',
        email:             'c.laurent@etu.novacampus.fr',
        birth_date:        new Date('2004-04-17'),
        enrollment_year:   2023,
        status:            'Actif',
        payment_status:    'À jour',
        address:           '67 Boulevard Tech',
        city:              'Toulouse',
        postal_code:       '31100',
        emergency_contact: 'Marc Laurent',
        emergency_phone:   '33620888888',
      },
      {
        student_id:        'STU009',
        campus_id:         'CAMP004',
        program_id:        'PROG005',
        first_name:        'Nathan',
        last_name:         'Girard',
        email:             'n.girard@etu.novacampus.fr',
        birth_date:        new Date('2003-12-03'),
        enrollment_year:   2023,
        status:            'Actif',
        payment_status:    'À jour',
        address:           '89 Rue Mer',
        city:              'Marseille',
        postal_code:       '13001',
        emergency_contact: 'Emma Girard',
        emergency_phone:   '33620999999',
      },
      {
        student_id:        'STU010',
        campus_id:         'CAMP001',
        program_id:        'PROG003',
        first_name:        'Manon',
        last_name:         'Lefebvre',
        email:             'm.lefebvre@etu.novacampus.fr',
        birth_date:        new Date('2002-08-28'),
        enrollment_year:   2022,
        status:            'Actif',
        payment_status:    'À jour',
        address:           '12 Place Latin',
        city:              'Paris',
        postal_code:       '75006',
        emergency_contact: 'Nicolas Lefebvre',
        emergency_phone:   '33620101010',
      },
      {
        student_id:        'STU011',
        campus_id:         'CAMP002',
        program_id:        'PROG001',
        first_name:        'Arthur',
        last_name:         'Garcia',
        email:             'a.garcia@etu.novacampus.fr',
        birth_date:        new Date('2004-02-14'),
        enrollment_year:   2023,
        status:            'Actif',
        payment_status:    'Retard',
        address:           '34 Rue Rhône',
        city:              'Lyon',
        postal_code:       '69002',
        emergency_contact: 'Léa Garcia',
        emergency_phone:   '33620121212',
      },
      {
        student_id:        'STU012',
        campus_id:         'CAMP001',
        program_id:        'PROG002',
        first_name:        'Jade',
        last_name:         'Martinez',
        email:             'j.martinez@etu.novacampus.fr',
        birth_date:        new Date('2003-10-21'),
        enrollment_year:   2023,
        status:            'Actif',
        payment_status:    'À jour',
        address:           '56 Avenue République',
        city:              'Paris',
        postal_code:       '75010',
        emergency_contact: 'Thomas Martinez',
        emergency_phone:   '33620131313',
      },
    ],
  });

  // ─── COURS ─────────────────────────────────────────────────────
  await prisma.course.createMany({
    data: [
      {
        course_id:     'CRS001',
        program_id:    'PROG001',
        instructor_id: 'INST001',
        room_id:       'ROOM101',
        course_name:   'Introduction au Commerce',
        course_code:   'COM101',
        semester:      1,
        credits:       6,
        hours_total:   45,
        status:        'Actif',
      },
      {
        course_id:     'CRS002',
        program_id:    'PROG003',
        instructor_id: 'INST003',
        room_id:       'ROOM205',
        course_name:   'Mathématiques Financières',
        course_code:   'FIN201',
        semester:      1,
        credits:       8,
        hours_total:   60,
        status:        'Actif',
      },
      {
        course_id:     'CRS003',
        program_id:    'PROG002',
        instructor_id: 'INST002',
        room_id:       'ROOM302',
        course_name:   'Programmation Python',
        course_code:   'INFO101',
        semester:      1,
        credits:       6,
        hours_total:   50,
        status:        'Actif',
      },
      {
        course_id:     'CRS004',
        program_id:    'PROG001',
        instructor_id: 'INST001',
        room_id:       'ROOM101',
        course_name:   'Marketing Stratégique',
        course_code:   'MKT301',
        semester:      2,
        credits:       6,
        hours_total:   45,
        status:        'Actif',
      },
      {
        course_id:     'CRS005',
        program_id:    'PROG002',
        instructor_id: 'INST002',
        room_id:       'ROOM303',
        course_name:   'Intelligence Artificielle',
        course_code:   'INFO301',
        semester:      2,
        credits:       8,
        hours_total:   65,
        status:        'Actif',
      },
      {
        course_id:     'CRS006',
        program_id:    'PROG004',
        instructor_id: 'INST004',
        room_id:       'ROOM401',
        course_name:   'Mécanique des Fluides',
        course_code:   'AERO201',
        semester:      1,
        credits:       7,
        hours_total:   55,
        status:        'Actif',
      },
      {
        course_id:     'CRS007',
        program_id:    'PROG006',
        instructor_id: 'INST005',
        room_id:       'ROOM201',
        course_name:   'Analyse de Données',
        course_code:   'DATA201',
        semester:      1,
        credits:       8,
        hours_total:   60,
        status:        'Actif',
      },
      {
        course_id:     'CRS008',
        program_id:    'PROG001',
        instructor_id: 'INST006',
        room_id:       'ROOM102',
        course_name:   'Économie Internationale',
        course_code:   'ECO101',
        semester:      1,
        credits:       5,
        hours_total:   40,
        status:        'Actif',
      },
      {
        course_id:     'CRS009',
        program_id:    'PROG003',
        instructor_id: 'INST007',
        room_id:       'ROOM206',
        course_name:   'Droit des Affaires',
        course_code:   'LAW201',
        semester:      1,
        credits:       6,
        hours_total:   45,
        status:        'Actif',
      },
      {
        course_id:     'CRS010',
        program_id:    'PROG002',
        instructor_id: 'INST002',
        room_id:       'ROOM304',
        course_name:   'Web Development',
        course_code:   'INFO201',
        semester:      1,
        credits:       7,
        hours_total:   55,
        status:        'Actif',
      },
    ],
  });

  // ─── PLANNINGS ─────────────────────────────────────────────────
  await prisma.schedule.createMany({
    data: [
      {
        schedule_id:   'SCH001',
        course_id:     'CRS001',
        instructor_id: 'INST001',
        room_id:       'ROOM101',
        day_of_week:   DAY['Lundi'],
        start_time:    t('09:00:00'),
        end_time:      t('12:00:00'),
        semester:      1,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2023-08-25'),
      },
      {
        schedule_id:   'SCH002',
        course_id:     'CRS003',
        instructor_id: 'INST002',
        room_id:       'ROOM302',
        day_of_week:   DAY['Mardi'],
        start_time:    t('14:00:00'),
        end_time:      t('17:00:00'),
        semester:      1,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2023-08-25'),
      },
      {
        schedule_id:   'SCH003',
        course_id:     'CRS002',
        instructor_id: 'INST003',
        room_id:       'ROOM205',
        day_of_week:   DAY['Mercredi'],
        start_time:    t('10:00:00'),
        end_time:      t('12:00:00'),
        semester:      1,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2023-08-25'),
      },
      {
        schedule_id:   'SCH004',
        course_id:     'CRS004',
        instructor_id: 'INST001',
        room_id:       'ROOM101',
        day_of_week:   DAY['Jeudi'],
        start_time:    t('14:00:00'),
        end_time:      t('17:00:00'),
        semester:      2,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2024-01-10'),
      },
      {
        schedule_id:   'SCH005',
        course_id:     'CRS005',
        instructor_id: 'INST002',
        room_id:       'ROOM303',
        day_of_week:   DAY['Vendredi'],
        start_time:    t('09:00:00'),
        end_time:      t('12:00:00'),
        semester:      2,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2024-01-10'),
      },
      {
        schedule_id:   'SCH006',
        course_id:     'CRS006',
        instructor_id: 'INST004',
        room_id:       'ROOM401',
        day_of_week:   DAY['Lundi'],
        start_time:    t('14:00:00'),
        end_time:      t('17:00:00'),
        semester:      1,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2023-08-25'),
      },
      {
        schedule_id:   'SCH007',
        course_id:     'CRS007',
        instructor_id: 'INST005',
        room_id:       'ROOM201',
        day_of_week:   DAY['Mardi'],
        start_time:    t('10:00:00'),
        end_time:      t('13:00:00'),
        semester:      1,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2023-08-25'),
      },
      {
        schedule_id:   'SCH008',
        course_id:     'CRS008',
        instructor_id: 'INST006',
        room_id:       'ROOM102',
        day_of_week:   DAY['Mercredi'],
        start_time:    t('14:00:00'),
        end_time:      t('16:00:00'),
        semester:      1,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2023-08-25'),
      },
      {
        schedule_id:   'SCH009',
        course_id:     'CRS009',
        instructor_id: 'INST007',
        room_id:       'ROOM206',
        day_of_week:   DAY['Jeudi'],
        start_time:    t('10:00:00'),
        end_time:      t('12:00:00'),
        semester:      1,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2023-08-25'),
      },
      {
        schedule_id:   'SCH010',
        course_id:     'CRS010',
        instructor_id: 'INST002',
        room_id:       'ROOM304',
        day_of_week:   DAY['Vendredi'],
        start_time:    t('14:00:00'),
        end_time:      t('17:00:00'),
        semester:      1,
        academic_year: '2023-2024',
        status:        'Actif',
        last_modified: new Date('2023-08-25'),
      },
    ],
  });

  // ─── INSCRIPTIONS ──────────────────────────────────────────────
  await prisma.enrollment.createMany({
    data: [
      {
        enrollment_id:   'ENR001',
        student_id:      'STU001',
        course_id:       'CRS001',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 95.0,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR002',
        student_id:      'STU001',
        course_id:       'CRS003',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 88.5,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR003',
        student_id:      'STU002',
        course_id:       'CRS003',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 92.0,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR004',
        student_id:      'STU002',
        course_id:       'CRS005',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 85.0,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR005',
        student_id:      'STU003',
        course_id:       'CRS001',
        semester:        2,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('Validé'),
        final_grade:     15.5,
        attendance_rate: 94.0,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR006',
        student_id:      'STU003',
        course_id:       'CRS004',
        semester:        2,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 91.0,
        enrollment_date: new Date('2024-01-15'),
      },
      {
        enrollment_id:   'ENR007',
        student_id:      'STU004',
        course_id:       'CRS002',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 89.0,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR008',
        student_id:      'STU004',
        course_id:       'CRS007',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 93.5,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR009',
        student_id:      'STU005',
        course_id:       'CRS006',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 87.0,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR010',
        student_id:      'STU006',
        course_id:       'CRS001',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 96.5,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR011',
        student_id:      'STU006',
        course_id:       'CRS008',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 91.5,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR012',
        student_id:      'STU007',
        course_id:       'CRS003',
        semester:        2,
        academic_year:   '2022-2023',
        status:          mapEnrollmentStatus('Validé'),
        final_grade:     14.0,
        attendance_rate: 82.0,
        enrollment_date: new Date('2022-09-01'),
      },
      {
        enrollment_id:   'ENR013',
        student_id:      'STU007',
        course_id:       'CRS010',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 79.0,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR014',
        student_id:      'STU008',
        course_id:       'CRS006',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 90.0,
        enrollment_date: new Date('2023-09-01'),
      },
      {
        enrollment_id:   'ENR015',
        student_id:      'STU009',
        course_id:       'CRS008',
        semester:        1,
        academic_year:   '2023-2024',
        status:          mapEnrollmentStatus('En cours'),
        final_grade:     null,
        attendance_rate: 88.0,
        enrollment_date: new Date('2023-09-01'),
      },
    ],
  });

  // ─── PAIEMENTS ─────────────────────────────────────────────────
  await prisma.payment.createMany({
    data: [
      {
        payment_id:     'PAY001',
        student_id:     'STU001',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         4250.0,
        status:         mapPaymentStatus('Payé'),
        payment_date:   new Date('2023-09-10'),
        payment_method: 'Virement',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Semestre 1',
      },
      {
        payment_id:     'PAY002',
        student_id:     'STU002',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         4500.0,
        status:         mapPaymentStatus('Retard'),
        payment_date:   null,
        payment_method: 'Virement',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Relance envoyée',
      },
      {
        payment_id:     'PAY003',
        student_id:     'STU003',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         4250.0,
        status:         mapPaymentStatus('Payé'),
        payment_date:   new Date('2023-09-08'),
        payment_method: 'Carte bancaire',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Semestre 1',
      },
      {
        payment_id:     'PAY004',
        student_id:     'STU004',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         6000.0,
        status:         mapPaymentStatus('Payé'),
        payment_date:   new Date('2023-09-12'),
        payment_method: 'Virement',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Semestre 1',
      },
      {
        payment_id:     'PAY005',
        student_id:     'STU005',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         4750.0,
        status:         mapPaymentStatus('Payé'),
        payment_date:   new Date('2023-09-05'),
        payment_method: 'Virement',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Semestre 1',
      },
      {
        payment_id:     'PAY006',
        student_id:     'STU006',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         4250.0,
        status:         mapPaymentStatus('Payé'),
        payment_date:   new Date('2023-09-11'),
        payment_method: 'Carte bancaire',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Semestre 1',
      },
      {
        payment_id:     'PAY007',
        student_id:     'STU007',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         4500.0,
        status:         mapPaymentStatus('Retard'),
        payment_date:   null,
        payment_method: 'Virement',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Relance 2ème niveau',
      },
      {
        payment_id:     'PAY008',
        student_id:     'STU008',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         4750.0,
        status:         mapPaymentStatus('Payé'),
        payment_date:   new Date('2023-09-07'),
        payment_method: 'Virement',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Semestre 1',
      },
      {
        payment_id:     'PAY009',
        student_id:     'STU009',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         3750.0,
        status:         mapPaymentStatus('Payé'),
        payment_date:   new Date('2023-09-09'),
        payment_method: 'Virement',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Semestre 1',
      },
      {
        payment_id:     'PAY010',
        student_id:     'STU010',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         6000.0,
        status:         mapPaymentStatus('Payé'),
        payment_date:   new Date('2023-09-13'),
        payment_method: 'Carte bancaire',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Semestre 1',
      },
      {
        payment_id:     'PAY011',
        student_id:     'STU011',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         4250.0,
        status:         mapPaymentStatus('Retard'),
        payment_date:   null,
        payment_method: 'Virement',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Relance envoyée',
      },
      {
        payment_id:     'PAY012',
        student_id:     'STU012',
        invoice_date:   new Date('2023-08-01'),
        due_date:       new Date('2023-09-15'),
        amount:         4500.0,
        status:         mapPaymentStatus('Payé'),
        payment_date:   new Date('2023-09-14'),
        payment_method: 'Virement',
        academic_year:  '2023-2024',
        semester:       1,
        notes:          'Semestre 1',
      },
    ],
  });

  // ─── KPI DASHBOARD ─────────────────────────────────────────────
  await prisma.kpiDashboard.createMany({
    data: [
      {
        period:                       '2023-2024 S1',
        campus_id:                    'CAMP001',
        total_students:               650,
        enrollment_rate_percent:      92.5,
        average_attendance_percent:   90.2,
        success_rate_percent:         88.5,
        revenue:                      2925000,
        payment_default_rate_percent: 8.2,
        room_occupancy_percent:       78.5,
      },
      {
        period:                       '2023-2024 S1',
        campus_id:                    'CAMP002',
        total_students:               420,
        enrollment_rate_percent:      88.3,
        average_attendance_percent:   89.5,
        success_rate_percent:         86.0,
        revenue:                      1890000,
        payment_default_rate_percent: 6.5,
        room_occupancy_percent:       72.3,
      },
      {
        period:                       '2023-2024 S1',
        campus_id:                    'CAMP003',
        total_students:               310,
        enrollment_rate_percent:      85.7,
        average_attendance_percent:   91.0,
        success_rate_percent:         89.2,
        revenue:                      1472500,
        payment_default_rate_percent: 5.1,
        room_occupancy_percent:       68.9,
      },
      {
        period:                       '2023-2024 S1',
        campus_id:                    'CAMP004',
        total_students:               225,
        enrollment_rate_percent:      78.5,
        average_attendance_percent:   87.8,
        success_rate_percent:         85.5,
        revenue:                      843750,
        payment_default_rate_percent: 9.8,
        room_occupancy_percent:       62.4,
      },
      {
        period:                       '2022-2023 S2',
        campus_id:                    'CAMP001',
        total_students:               625,
        enrollment_rate_percent:      91.2,
        average_attendance_percent:   89.8,
        success_rate_percent:         87.2,
        revenue:                      2812500,
        payment_default_rate_percent: 7.5,
        room_occupancy_percent:       76.8,
      },
      {
        period:                       '2022-2023 S2',
        campus_id:                    'CAMP002',
        total_students:               390,
        enrollment_rate_percent:      86.5,
        average_attendance_percent:   88.9,
        success_rate_percent:         85.5,
        revenue:                      1755000,
        payment_default_rate_percent: 7.2,
        room_occupancy_percent:       70.1,
      },
    ],
  });

  // ─── UTILISATEURS ──────────────────────────────────────────────
  // Comptes techniques de test
  const adminAccounts = [
    {
      email:      'admin@novacampus.fr',
      role:       Role.ADMIN,
      first_name: 'Sophie',
      last_name:  'Bernard',
      campus_id:  'CAMP001',
    },
    {
      email:      'direction@novacampus.fr',
      role:       Role.DIRECTION,
      first_name: 'Pierre',
      last_name:  'Leroy',
      campus_id:  'CAMP001',
    },
  ];
  await prisma.user.createMany({
    data: await Promise.all(
      adminAccounts.map(async (u) => {
        const password = seedPassword(u.role, u.first_name);
        seededPasswords.push({ email: u.email, password });
        return {
          email:         u.email,
          password_hash: await hashPassword(password),
          role:          u.role,
          first_name:    u.first_name,
          last_name:     u.last_name,
          campus_id:     u.campus_id,
          is_active:     true,
        };
      }),
    ),
  });

  // Comptes enseignants
  const instructorAccounts = [
    { email: 'j.mercier@novacampus.fr',  first_name: 'Jean',   last_name: 'Mercier',  campus_id: 'CAMP001' },
    { email: 'm.dubois@novacampus.fr',   first_name: 'Marie',  last_name: 'Dubois',   campus_id: 'CAMP001' },
    { email: 'p.laurent@novacampus.fr',  first_name: 'Pierre', last_name: 'Laurent',  campus_id: 'CAMP001' },
    { email: 's.rousseau@novacampus.fr', first_name: 'Sophie', last_name: 'Rousseau', campus_id: 'CAMP003' },
    { email: 'c.martin@novacampus.fr',   first_name: 'Claire', last_name: 'Martin',   campus_id: 'CAMP002' },
    { email: 't.bernard@novacampus.fr',  first_name: 'Thomas', last_name: 'Bernard',  campus_id: 'CAMP001' },
    { email: 'l.faure@novacampus.fr',    first_name: 'Luc',    last_name: 'Faure',    campus_id: 'CAMP001' },
    { email: 'j.simon@novacampus.fr',    first_name: 'Julie',  last_name: 'Simon',    campus_id: 'CAMP002' },
  ];
  await prisma.user.createMany({
    data: await Promise.all(
      instructorAccounts.map(async (u) => {
        const password = seedPassword(Role.INSTRUCTOR, u.first_name);
        seededPasswords.push({ email: u.email, password });
        return {
          email:         u.email,
          password_hash: await hashPassword(password),
          role:          Role.INSTRUCTOR,
          first_name:    u.first_name,
          last_name:     u.last_name,
          campus_id:     u.campus_id,
          is_active:     true,
        };
      }),
    ),
  });

  // Comptes étudiants (liés aux enregistrements Student)
  const studentAccounts = [
    { email: 'a.dubois@etu.novacampus.fr',   first_name: 'Alexandre', last_name: 'Dubois',   student_id: 'STU001', campus_id: 'CAMP001' },
    { email: 'c.martin@etu.novacampus.fr',   first_name: 'Camille',   last_name: 'Martin',   student_id: 'STU002', campus_id: 'CAMP001' },
    { email: 'l.bernard@etu.novacampus.fr',  first_name: 'Lucas',     last_name: 'Bernard',  student_id: 'STU003', campus_id: 'CAMP002' },
    { email: 'e.petit@etu.novacampus.fr',    first_name: 'Emma',      last_name: 'Petit',    student_id: 'STU004', campus_id: 'CAMP002' },
    { email: 't.roux@etu.novacampus.fr',     first_name: 'Thomas',    last_name: 'Roux',     student_id: 'STU005', campus_id: 'CAMP003' },
    { email: 'l.moreau@etu.novacampus.fr',   first_name: 'Léa',       last_name: 'Moreau',   student_id: 'STU006', campus_id: 'CAMP001' },
    { email: 'h.simon@etu.novacampus.fr',    first_name: 'Hugo',      last_name: 'Simon',    student_id: 'STU007', campus_id: 'CAMP002' },
    { email: 'c.laurent@etu.novacampus.fr',  first_name: 'Chloé',     last_name: 'Laurent',  student_id: 'STU008', campus_id: 'CAMP003' },
    { email: 'n.girard@etu.novacampus.fr',   first_name: 'Nathan',    last_name: 'Girard',   student_id: 'STU009', campus_id: 'CAMP004' },
    { email: 'm.lefebvre@etu.novacampus.fr', first_name: 'Manon',     last_name: 'Lefebvre', student_id: 'STU010', campus_id: 'CAMP001' },
    { email: 'a.garcia@etu.novacampus.fr',   first_name: 'Arthur',    last_name: 'Garcia',   student_id: 'STU011', campus_id: 'CAMP002' },
    { email: 'j.martinez@etu.novacampus.fr', first_name: 'Jade',      last_name: 'Martinez', student_id: 'STU012', campus_id: 'CAMP001' },
  ];
  await prisma.user.createMany({
    data: await Promise.all(
      studentAccounts.map(async (u) => {
        const password = seedPassword(Role.STUDENT, u.first_name);
        seededPasswords.push({ email: u.email, password });
        return {
          email:         u.email,
          password_hash: await hashPassword(password),
          role:          Role.STUDENT,
          first_name:    u.first_name,
          last_name:     u.last_name,
          student_id:    u.student_id,
          campus_id:     u.campus_id,
          is_active:     true,
        };
      }),
    ),
  });

  console.log('Seed terminé avec succès :');
  console.log('  4 campus, 7 programmes, 8 enseignants, 10 salles');
  console.log('  12 étudiants, 10 cours, 10 plannings');
  console.log('  15 inscriptions, 12 paiements, 6 entrées KPI');
  console.log('  22 utilisateurs (2 admin/direction + 8 enseignants + 12 étudiants)');
  console.log('  Mots de passe par compte :');
  for (const { email, password } of seededPasswords) {
    console.log(`    ${email} → ${password}`);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
