content = open('scripts/create_issues.py', encoding='utf-8').read()
content = content.replace('"milestone": "1"', '"milestone": "M1 \u2014 Infrastructure & Setup"')
content = content.replace('"milestone": "2"', '"milestone": "M2 \u2014 Svc Acad\u00e9mique"')
content = content.replace('"milestone": "3"', '"milestone": "M3 \u2014 Svc Facturation"')
content = content.replace('"milestone": "4"', '"milestone": "M4 \u2014 Portails IHM"')
content = content.replace('"milestone": "5"', '"milestone": "M5 \u2014 Svc Notification"')
content = content.replace('"milestone": "6"', '"milestone": "M6 \u2014 Dashboard Direction & KPIs"')
content = content.replace('"milestone": "7"', '"milestone": "M7 \u2014 Agent IA"')
open('scripts/create_issues.py', 'w', encoding='utf-8').write(content)
print('done')
