/**
 * Donnees de demonstration utilisees tant que les endpoints backend ne sont pas
 * branches. Chaque fonction `fetchX` du fichier `api.ts` essaie d'abord l'API
 * reelle et retombe sur ces mocks si le backend n'est pas disponible.
 */

import { UserRole } from './auth';
import {
  AdminStudent,
  AppNotification,
  CourseGrade,
  DashboardStudent,
  EnrolledStudent,
  Invoice,
  PaymentAlert,
  PaymentRow,
  Room,
  ScheduleConflict,
  ScheduleSlot,
  StudentHistory,
  TeacherCourse,
  TeacherHistoryEntry,
  TranscriptEntry,
} from './types';

function isoAt(dayOffset: number, hour: number, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

const mondayOffset = (() => {
  const today = new Date().getDay(); // 0=dim ... 6=sam
  return today === 0 ? -6 : 1 - today;
})();

export const MOCK_SCHEDULE: ScheduleSlot[] = [
  {
    id: 's1',
    courseId: 'c-info-101',
    courseName: 'Algorithmique avancee',
    instructorName: 'Mme Dupont',
    roomId: 'r-a204',
    roomName: 'A204',
    campus: 'Paris',
    startsAt: isoAt(mondayOffset, 9),
    endsAt: isoAt(mondayOffset, 11),
    studentGroup: 'L3-INFO-A',
  },
  {
    id: 's2',
    courseId: 'c-math-220',
    courseName: 'Algebre lineaire',
    instructorName: 'M. Bernard',
    roomId: 'r-b105',
    roomName: 'B105',
    campus: 'Paris',
    startsAt: isoAt(mondayOffset, 14),
    endsAt: isoAt(mondayOffset, 16),
    studentGroup: 'L3-INFO-A',
  },
  {
    id: 's3',
    courseId: 'c-eng-150',
    courseName: 'Anglais professionnel',
    instructorName: 'Ms. Carter',
    roomId: 'r-c310',
    roomName: 'C310',
    campus: 'Paris',
    startsAt: isoAt(mondayOffset + 1, 10),
    endsAt: isoAt(mondayOffset + 1, 12),
    studentGroup: 'L3-INFO-A',
  },
  {
    id: 's4',
    courseId: 'c-info-220',
    courseName: 'Bases de donnees',
    instructorName: 'M. Lefebvre',
    roomId: 'r-a204',
    roomName: 'A204',
    campus: 'Paris',
    startsAt: isoAt(mondayOffset + 2, 9),
    endsAt: isoAt(mondayOffset + 2, 12),
    studentGroup: 'L3-INFO-A',
  },
  {
    id: 's5',
    courseId: 'c-info-310',
    courseName: 'Architecture micro-services',
    instructorName: 'M. Moreau',
    roomId: 'r-a210',
    roomName: 'A210',
    campus: 'Paris',
    startsAt: isoAt(mondayOffset + 3, 13, 30),
    endsAt: isoAt(mondayOffset + 3, 17),
    studentGroup: 'L3-INFO-A',
  },
  {
    id: 's6',
    courseId: 'c-pm-100',
    courseName: 'Gestion de projet',
    instructorName: 'Mme Petit',
    roomId: 'r-b105',
    roomName: 'B105',
    campus: 'Paris',
    startsAt: isoAt(mondayOffset + 4, 9),
    endsAt: isoAt(mondayOffset + 4, 12),
    studentGroup: 'L3-INFO-A',
  },
];

export const MOCK_GRADES: CourseGrade[] = [
  {
    courseId: 'c-info-101',
    courseCode: 'INFO101',
    courseName: 'Algorithmique avancee',
    finalGrade: 14.5,
    maxGrade: 20,
    attendanceRate: 0.96,
    status: 'VALIDE',
    ects: 6,
    semester: 'S5',
  },
  {
    courseId: 'c-math-220',
    courseCode: 'MATH220',
    courseName: 'Algebre lineaire',
    finalGrade: 11,
    maxGrade: 20,
    attendanceRate: 0.88,
    status: 'VALIDE',
    ects: 5,
    semester: 'S5',
  },
  {
    courseId: 'c-eng-150',
    courseCode: 'ENG150',
    courseName: 'Anglais professionnel',
    finalGrade: 16,
    maxGrade: 20,
    attendanceRate: 1,
    status: 'VALIDE',
    ects: 3,
    semester: 'S5',
  },
  {
    courseId: 'c-info-220',
    courseCode: 'INFO220',
    courseName: 'Bases de donnees',
    finalGrade: null,
    maxGrade: 20,
    attendanceRate: 0.83,
    status: 'EN_COURS',
    ects: 6,
    semester: 'S5',
  },
  {
    courseId: 'c-info-310',
    courseCode: 'INFO310',
    courseName: 'Architecture micro-services',
    finalGrade: 8,
    maxGrade: 20,
    attendanceRate: 0.72,
    status: 'RATTRAPAGE',
    ects: 0,
    semester: 'S5',
  },
];

export const MOCK_TRANSCRIPT: TranscriptEntry[] = [
  {
    semester: 'S3',
    averageGrade: 13.2,
    ectsEarned: 28,
    courses: [
      {
        courseId: 't1',
        courseCode: 'INFO050',
        courseName: 'Introduction informatique',
        finalGrade: 15,
        maxGrade: 20,
        attendanceRate: 0.94,
        status: 'VALIDE',
        ects: 6,
        semester: 'S3',
      },
      {
        courseId: 't2',
        courseCode: 'MATH101',
        courseName: 'Analyse 1',
        finalGrade: 12,
        maxGrade: 20,
        attendanceRate: 0.86,
        status: 'VALIDE',
        ects: 5,
        semester: 'S3',
      },
    ],
  },
  {
    semester: 'S4',
    averageGrade: 12.6,
    ectsEarned: 30,
    courses: [
      {
        courseId: 't3',
        courseCode: 'INFO080',
        courseName: 'Programmation orientee objet',
        finalGrade: 14,
        maxGrade: 20,
        attendanceRate: 0.91,
        status: 'VALIDE',
        ects: 6,
        semester: 'S4',
      },
      {
        courseId: 't4',
        courseCode: 'STAT110',
        courseName: 'Statistiques',
        finalGrade: 11,
        maxGrade: 20,
        attendanceRate: 0.8,
        status: 'VALIDE',
        ects: 5,
        semester: 'S4',
      },
    ],
  },
  {
    semester: 'S5',
    averageGrade: 12.4,
    ectsEarned: 14,
    courses: MOCK_GRADES,
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    reference: 'F-2025-00451',
    studentId: 'me',
    amount: 2500,
    currency: 'EUR',
    status: 'PAID',
    issuedAt: '2025-09-01T08:00:00.000Z',
    dueAt: '2025-09-30T23:59:59.000Z',
    paidAt: '2025-09-15T10:21:00.000Z',
    description: 'Frais de scolarite — S5',
    lines: [
      { label: 'Frais de scolarite S5', quantity: 1, unitPrice: 2200 },
      { label: 'Cotisation BDE', quantity: 1, unitPrice: 80 },
      { label: 'Plateforme numerique', quantity: 1, unitPrice: 220 },
    ],
  },
  {
    id: 'inv-002',
    reference: 'F-2026-00128',
    studentId: 'me',
    amount: 2500,
    currency: 'EUR',
    status: 'PENDING',
    issuedAt: '2026-01-10T08:00:00.000Z',
    dueAt: '2026-06-30T23:59:59.000Z',
    description: 'Frais de scolarite — S6',
    lines: [
      { label: 'Frais de scolarite S6', quantity: 1, unitPrice: 2200 },
      { label: 'Cotisation BDE', quantity: 1, unitPrice: 80 },
      { label: 'Plateforme numerique', quantity: 1, unitPrice: 220 },
    ],
  },
  {
    id: 'inv-003',
    reference: 'F-2025-00802',
    studentId: 'me',
    amount: 320,
    currency: 'EUR',
    status: 'OVERDUE',
    issuedAt: '2025-11-05T08:00:00.000Z',
    dueAt: '2025-12-05T23:59:59.000Z',
    description: 'Sortie pedagogique — Voyage Berlin',
    lines: [{ label: 'Voyage pedagogique Berlin', quantity: 1, unitPrice: 320 }],
  },
];

export const MOCK_ENROLLED_STUDENTS: EnrolledStudent[] = [
  {
    id: 'st-1',
    firstName: 'Alice',
    lastName: 'Martin',
    email: 'alice.martin@novacampus.fr',
    currentGrade: 14,
    attendanceRate: 0.95,
  },
  {
    id: 'st-2',
    firstName: 'Hugo',
    lastName: 'Bernard',
    email: 'hugo.bernard@novacampus.fr',
    currentGrade: 11.5,
    attendanceRate: 0.82,
  },
  {
    id: 'st-3',
    firstName: 'Lea',
    lastName: 'Dubois',
    email: 'lea.dubois@novacampus.fr',
    currentGrade: 17,
    attendanceRate: 1,
  },
  {
    id: 'st-4',
    firstName: 'Karim',
    lastName: 'Benali',
    email: 'karim.benali@novacampus.fr',
    currentGrade: 9,
    attendanceRate: 0.7,
  },
  {
    id: 'st-5',
    firstName: 'Sofia',
    lastName: 'Garcia',
    email: 'sofia.garcia@novacampus.fr',
    currentGrade: null,
    attendanceRate: 0.88,
  },
];

export const MOCK_TEACHER_COURSES: TeacherCourse[] = [
  {
    id: 'c-info-101',
    code: 'INFO101',
    name: 'Algorithmique avancee',
    campus: 'Paris',
    program: 'L3 INFO',
    enrolledCount: 28,
    successRate: 0.82,
    averageGrade: 13.4,
    roomId: 'r-a204',
    roomName: 'A204',
    resources: ['Videoprojecteur'],
  },
  {
    id: 'c-info-220',
    code: 'INFO220',
    name: 'Bases de donnees',
    campus: 'Paris',
    program: 'L3 INFO',
    enrolledCount: 31,
    successRate: 0.74,
    averageGrade: 12.1,
    roomId: 'r-b105',
    roomName: 'B105',
    resources: ['Videoprojecteur', 'Postes informatiques'],
  },
  {
    id: 'c-info-310',
    code: 'INFO310',
    name: 'Architecture micro-services',
    campus: 'Paris',
    program: 'M1 INFO',
    enrolledCount: 22,
    successRate: 0.68,
    averageGrade: 11.6,
  },
];

export const MOCK_ROOMS: Room[] = [
  { id: 'r-a204', name: 'A204', campus: 'Paris', capacity: 32, type: 'Salle TD', occupancy: 0.78 },
  { id: 'r-a210', name: 'A210', campus: 'Paris', capacity: 32, type: 'Salle TD', occupancy: 0.45 },
  { id: 'r-amph1', name: 'Amphi 1', campus: 'Paris', capacity: 120, type: 'Amphi', occupancy: 0.62 },
  { id: 'r-b105', name: 'B105', campus: 'Paris', capacity: 28, type: 'Salle TP', occupancy: 0.9 },
  { id: 'r-l1', name: 'Labo Info 1', campus: 'Lyon', capacity: 24, type: 'Labo', occupancy: 0.55 },
  { id: 'r-c310', name: 'C310', campus: 'Lyon', capacity: 35, type: 'Salle TD', occupancy: 0.3 },
  { id: 'r-t1', name: 'Hangar T1', campus: 'Toulouse', capacity: 40, type: 'Labo', occupancy: 0.48 },
];

export const MOCK_TEACHER_HISTORY: TeacherHistoryEntry[] = [
  {
    id: 'h-1',
    semester: 'S4 2025-2026',
    courseCode: 'INFO101',
    courseName: 'Algorithmique avancee',
    group: 'L3-INFO-A',
    campus: 'Paris',
    studentsCount: 26,
    averageGrade: 12.8,
    successRate: 0.81,
  },
  {
    id: 'h-2',
    semester: 'S4 2025-2026',
    courseCode: 'INFO220',
    courseName: 'Bases de donnees',
    group: 'L3-INFO-B',
    campus: 'Paris',
    studentsCount: 29,
    averageGrade: 11.9,
    successRate: 0.72,
  },
  {
    id: 'h-3',
    semester: 'S3 2024-2025',
    courseCode: 'INFO101',
    courseName: 'Algorithmique avancee',
    group: 'L3-INFO-A',
    campus: 'Paris',
    studentsCount: 30,
    averageGrade: 13.1,
    successRate: 0.84,
  },
  {
    id: 'h-4',
    semester: 'S3 2024-2025',
    courseCode: 'INFO050',
    courseName: 'Introduction informatique',
    group: 'L1-INFO-C',
    campus: 'Lyon',
    studentsCount: 38,
    averageGrade: 12.2,
    successRate: 0.76,
  },
];

export const MOCK_STUDENT_HISTORY: StudentHistory[] = [
  {
    id: 'st-1',
    name: 'Alice Martin',
    email: 'alice.martin@novacampus.fr',
    courses: [
      { semester: 'S5 2026', courseCode: 'INFO101', courseName: 'Algorithmique avancee', grade: 14, attendanceRate: 0.95 },
      { semester: 'S4 2025-2026', courseCode: 'INFO220', courseName: 'Bases de donnees', grade: 13, attendanceRate: 0.9 },
    ],
  },
  {
    id: 'st-2',
    name: 'Hugo Bernard',
    email: 'hugo.bernard@novacampus.fr',
    courses: [
      { semester: 'S5 2026', courseCode: 'INFO101', courseName: 'Algorithmique avancee', grade: 11.5, attendanceRate: 0.82 },
      { semester: 'S3 2024-2025', courseCode: 'INFO050', courseName: 'Introduction informatique', grade: 12, attendanceRate: 0.88 },
    ],
  },
  {
    id: 'st-3',
    name: 'Lea Dubois',
    email: 'lea.dubois@novacampus.fr',
    courses: [
      { semester: 'S5 2026', courseCode: 'INFO220', courseName: 'Bases de donnees', grade: null, attendanceRate: 0.79 },
      { semester: 'S4 2025-2026', courseCode: 'INFO220', courseName: 'Bases de donnees', grade: 10.5, attendanceRate: 0.84 },
    ],
  },
  {
    id: 'st-4',
    name: 'Karim Benali',
    email: 'karim.benali@novacampus.fr',
    courses: [
      { semester: 'S4 2025-2026', courseCode: 'INFO101', courseName: 'Algorithmique avancee', grade: 15.5, attendanceRate: 0.97 },
    ],
  },
];

export const MOCK_ADMIN_STUDENTS: AdminStudent[] = [
  {
    id: 'st-1',
    firstName: 'Alice',
    lastName: 'Martin',
    email: 'alice.martin@novacampus.fr',
    campus: 'Paris',
    program: 'L3 INFO',
    status: 'ACTIF',
    enrolledCourses: 6,
  },
  {
    id: 'st-2',
    firstName: 'Hugo',
    lastName: 'Bernard',
    email: 'hugo.bernard@novacampus.fr',
    campus: 'Paris',
    program: 'L3 INFO',
    status: 'ACTIF',
    enrolledCourses: 6,
  },
  {
    id: 'st-3',
    firstName: 'Lea',
    lastName: 'Dubois',
    email: 'lea.dubois@novacampus.fr',
    campus: 'Lyon',
    program: 'M1 INFO',
    status: 'ACTIF',
    enrolledCourses: 5,
  },
  {
    id: 'st-4',
    firstName: 'Karim',
    lastName: 'Benali',
    email: 'karim.benali@novacampus.fr',
    campus: 'Marseille',
    program: 'L2 INFO',
    status: 'ACTIF',
    enrolledCourses: 7,
  },
  {
    id: 'st-5',
    firstName: 'Sofia',
    lastName: 'Garcia',
    email: 'sofia.garcia@novacampus.fr',
    campus: 'Paris',
    program: 'M2 INFO',
    status: 'DIPLOME',
    enrolledCourses: 0,
  },
  {
    id: 'st-6',
    firstName: 'Thomas',
    lastName: 'Lefevre',
    email: 'thomas.lefevre@novacampus.fr',
    campus: 'Lyon',
    program: 'L1 INFO',
    status: 'INACTIF',
    enrolledCourses: 0,
  },
];

export const MOCK_CONFLICTS: ScheduleConflict[] = [
  {
    id: 'conf-1',
    severity: 'CRITICAL',
    reason: 'Salle A204 reservee simultanement pour 2 cours',
    slots: [MOCK_SCHEDULE[0], MOCK_SCHEDULE[3]],
    suggestedRooms: [
      { roomId: 'r-a210', roomName: 'A210', capacity: 32 },
      { roomId: 'r-b202', roomName: 'B202', capacity: 28 },
    ],
  },
  {
    id: 'conf-2',
    severity: 'WARNING',
    reason: 'Capacite salle insuffisante (35 inscrits, capacite 28)',
    slots: [MOCK_SCHEDULE[2]],
    suggestedRooms: [{ roomId: 'r-amph1', roomName: 'Amphi 1', capacity: 80 }],
  },
];

export const MOCK_DASHBOARD_STUDENTS: DashboardStudent[] = [
  {
    id: 'st-1',
    name: 'Alexandre Dubois',
    email: 'a.dubois@etu.novacampus.fr',
    campus: 'Paris',
    filiere: 'Commerce',
    promotion: '2023',
    paymentStatus: 'PAID',
    reminders: 0,
  },
  {
    id: 'st-2',
    name: 'Camille Martin',
    email: 'c.martin@etu.novacampus.fr',
    campus: 'Paris',
    filiere: 'Informatique',
    promotion: '2023',
    paymentStatus: 'OVERDUE',
    reminders: 1,
  },
  {
    id: 'st-3',
    name: 'Lucas Bernard',
    email: 'l.bernard@etu.novacampus.fr',
    campus: 'Lyon',
    filiere: 'Commerce',
    promotion: '2022',
    paymentStatus: 'PAID',
    reminders: 0,
  },
  {
    id: 'st-4',
    name: 'Hugo Simon',
    email: 'h.simon@etu.novacampus.fr',
    campus: 'Lyon',
    filiere: 'Informatique',
    promotion: '2022',
    paymentStatus: 'OVERDUE',
    reminders: 2,
  },
  {
    id: 'st-5',
    name: 'Thomas Roux',
    email: 't.roux@etu.novacampus.fr',
    campus: 'Toulouse',
    filiere: 'Aerospatial',
    promotion: '2023',
    paymentStatus: 'PAID',
    reminders: 0,
  },
  {
    id: 'st-6',
    name: 'Arthur Garcia',
    email: 'a.garcia@etu.novacampus.fr',
    campus: 'Lyon',
    filiere: 'Commerce',
    promotion: '2023',
    paymentStatus: 'OVERDUE',
    reminders: 1,
  },
];

export const MOCK_PAYMENT_ALERTS: PaymentAlert[] = [
  {
    id: 'st-2',
    studentName: 'Camille Martin',
    amount: 4500,
    detail: 'Echeance depassee',
    reminderLevel: 1,
  },
  {
    id: 'st-4',
    studentName: 'Hugo Simon',
    amount: 4500,
    detail: '45 jours de retard',
    reminderLevel: 2,
  },
  {
    id: 'st-6',
    studentName: 'Arthur Garcia',
    amount: 4250,
    detail: 'Relance envoyee',
    reminderLevel: 1,
  },
];

export const MOCK_PAYMENTS: PaymentRow[] = [
  {
    invoiceId: 'inv-001',
    reference: 'F-2025-00451',
    studentName: 'Alice Martin',
    studentId: 'st-1',
    campus: 'Paris',
    amount: 2500,
    status: 'PAID',
    dueAt: '2025-09-30T23:59:59.000Z',
    remindersSent: 0,
  },
  {
    invoiceId: 'inv-002',
    reference: 'F-2026-00128',
    studentName: 'Hugo Bernard',
    studentId: 'st-2',
    campus: 'Paris',
    amount: 2500,
    status: 'PENDING',
    dueAt: '2026-06-30T23:59:59.000Z',
    remindersSent: 1,
  },
  {
    invoiceId: 'inv-003',
    reference: 'F-2025-00802',
    studentName: 'Lea Dubois',
    studentId: 'st-3',
    campus: 'Lyon',
    amount: 320,
    status: 'OVERDUE',
    dueAt: '2025-12-05T23:59:59.000Z',
    remindersSent: 3,
  },
  {
    invoiceId: 'inv-004',
    reference: 'F-2026-00203',
    studentName: 'Karim Benali',
    studentId: 'st-4',
    campus: 'Marseille',
    amount: 2200,
    status: 'OVERDUE',
    dueAt: '2026-04-15T23:59:59.000Z',
    remindersSent: 2,
  },
  {
    invoiceId: 'inv-005',
    reference: 'F-2026-00204',
    studentName: 'Sofia Garcia',
    studentId: 'st-5',
    campus: 'Paris',
    amount: 1800,
    status: 'PENDING',
    dueAt: '2026-07-10T23:59:59.000Z',
    remindersSent: 0,
  },
];

/**
 * Notifications par role : chaque portail recoit des alertes alignees sur ses
 * capacites (etudiant = changements/echeances, enseignant = saisies/salles,
 * admin = paiements/conflits, direction = rapports/indicateurs).
 */
export const MOCK_NOTIFICATIONS: Record<UserRole, AppNotification[]> = {
  STUDENT: [
    {
      id: 'n-s1',
      kind: 'SCHEDULE',
      title: 'Changement de salle',
      detail: 'Bases de donnees (mercredi 9h) deplace en salle B210.',
      date: isoAt(0, 8, 15),
      href: '/etudiant/planning',
      read: false,
    },
    {
      id: 'n-s2',
      kind: 'DEADLINE',
      title: 'Echeance de paiement',
      detail: 'Facture F-2026-00128 a regler avant le 30 juin.',
      date: isoAt(-1, 17, 30),
      href: '/etudiant/factures',
      read: false,
    },
    {
      id: 'n-s3',
      kind: 'GRADE',
      title: 'Note publiee',
      detail: 'Votre note d’Algorithmique avancee est disponible.',
      date: isoAt(-2, 11, 0),
      href: '/etudiant/notes',
      read: true,
    },
  ],
  INSTRUCTOR: [
    {
      id: 'n-t1',
      kind: 'SCHEDULE',
      title: 'Salle attribuee',
      detail: 'Salle C310 confirmee pour Anglais professionnel (jeudi 10h).',
      date: isoAt(0, 7, 45),
      href: '/enseignant/planning',
      read: false,
    },
    {
      id: 'n-t2',
      kind: 'DEADLINE',
      title: 'Saisie des notes attendue',
      detail: 'Les notes de Bases de donnees sont attendues avant vendredi.',
      date: isoAt(-1, 9, 0),
      href: '/enseignant/cours',
      read: false,
    },
    {
      id: 'n-t3',
      kind: 'SCHEDULE',
      title: 'Emploi du temps mis a jour',
      detail: 'Votre creneau du lundi 14h est deplace en salle B105.',
      date: isoAt(-3, 16, 20),
      href: '/enseignant/planning',
      read: true,
    },
  ],
  ADMIN: [
    {
      id: 'n-a1',
      kind: 'CONFLICT',
      title: 'Conflit de salle detecte',
      detail: 'Deux cours reserves en A204 mercredi 9h. Resolution requise.',
      date: isoAt(0, 8, 0),
      href: '/admin/conflits',
      read: false,
    },
    {
      id: 'n-a2',
      kind: 'PAYMENT',
      title: 'Paiements en retard',
      detail: '3 factures depassent 30 jours de retard. Relances a envoyer.',
      date: isoAt(-1, 10, 30),
      href: '/admin/paiements',
      read: false,
    },
    {
      id: 'n-a3',
      kind: 'REPORT',
      title: 'Nouvelles inscriptions',
      detail: '12 dossiers d’inscription recus cette semaine a valider.',
      date: isoAt(-2, 14, 10),
      href: '/admin/inscriptions',
      read: true,
    },
  ],
  DIRECTION: [
    {
      id: 'n-d1',
      kind: 'REPORT',
      title: 'Rapport mensuel disponible',
      detail: 'Indicateurs de mai consolides pour les trois campus.',
      date: isoAt(0, 9, 0),
      href: '/direction',
      read: false,
    },
    {
      id: 'n-d2',
      kind: 'REPORT',
      title: 'Occupation des salles',
      detail: 'Taux d’occupation de Lyon en hausse de 6 points ce mois.',
      date: isoAt(-2, 14, 0),
      href: '/direction',
      read: true,
    },
  ],
};
