name: CD - Deploy to IONOS VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            PROJECT_PATH="/home/${{ secrets.VPS_USER }}/novacampus_alliance"
            cd $PROJECT_PATH
            export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock
            bash deploy.sh